### PR TITLE
Use the system NSS CA trust library

### PR DESCRIPTION
**Pull request by special**
Quoting the commit:

```
[xulrunner] Use the system NSS CA trust library instead of the bundled copy

With the addition of p11-kit, we want to unify the CA trust stores
across the platform. p11-kit integrates with NSS by replacing
libnssckbi, the CA trust library, with a binary compatible version that
accesses the p11-kit store.

This is implemented in the system-wide nss and p11-kit packages by replacing a
subpackage that contains this library. For this browser version, so long
as we can rely on the ABI being compatible between browser nss, system nss,
and p11-kit, we can simply symlink to the system library and get the
same results.
```

Requires https://git.merproject.org/mer-core/nss/merge_requests/3 (for the nss-ckbi subpackage).

### CODE REVIEW

**Comment by rojkov** [comment]
Also --with-system-nss needs to be added to ./configure

We used to use the system NSS in the beginning, but had to switch to the internal lib because Gecko depended on unreleased NSS's code. Currently I'm working on the engine update gecko31 ->gecko35 and the newer engine uses NSS 3.17.2. Also the latest available embedlite code uses NSS 3.18Beta. I need to check if the engine still compiles with the outdated NSS.

**Comment by special** [comment]
Using system NSS would solve this problem, but it's actually a different solution. With this PR, gecko still uses its bundled NSS, _except_ for the libnssckbi library, which uses the system's version (which will actually be from p11-kit).

From what I understand, the ABI should be absolutely stable and this shouldn't be a problem. Other distributions have similar solutions.

Would you prefer switching to system NSS entirely?

**Comment by rojkov** [comment]
Alright. I misread the comment, but now I see your point. Looks nice actually. I'd like to give it a try once the pull request for nss-ckbi gets accepted.

**Comment by thp** [comment]
What's the status of this, @special @rojkov?

**Comment by rojkov** [comment]
@thp still pending https://git.merproject.org/mer-core/nss/merge_requests/3

**Comment by tigeli** [comment]
@rojkov nss MR/PR has been merged.

**Pull request merged**
