### PR TITLE
Improve rotation/size change performance.

### PR DESCRIPTION
**Pull request by tworaz**

### CODE REVIEW

**Comment by rainemak** [comment]
Could you split this into two PRs. One that contains only upstream patches and one that contains embedlite changes.

**Comment by tworaz** [comment]
Done, see PR #53

**Comment by rojkov** [comment]
LGTM

**Comment by rainemak** [comment]
Obsoleted by https://git.merproject.org/mer-core/gecko-dev/merge_requests/19

**Pull request closed without merging**
