### PR TITLE
[xulrunner] Change glClear color of OGL Compositor to white

### PR DESCRIPTION
**Pull request by rainemak**

### CODE REVIEW

**Comment by tmeshkova** [comment]
Why transparent color isn't good? don't we want to render Qt background through transparent gecko content?

**Comment by rainemak** [comment]
Clear color is not transparent but opaque black.

Idea is that gecko content is rendered to the background window. Chrome window will be on top of this one. Only those two windows will be used (two surfaces)  => chrome cannot draw background behind gecko content. In the area where we do not have tiles result is a black. Thus, changing the clear color to white.

**Comment by tmeshkova** [comment]
Would it be easier to fill with white color that background window? so we would have ability to control that on embedding side?

**Comment by rainemak** [comment]
To clarify are you after adding DrawWindowUnderlay for the EmbedLitePuppetWidget similar to Android FF? We could pass that call through to the QtMozEmbed. Indeed that would allow more customization.

**Comment by tmeshkova** [comment]
yep, something like DrawWindowUnderlay

**Comment by rainemak** [comment]
Closing as obsolete

**Pull request closed without merging**
