### PR TITLE
[xulrunner] Clear layer caches more aggressively. Contributes to JB#30573

### PR DESCRIPTION
**Pull request by tworaz**
This patchset back-ports changes from b2g v32 which allow the engine to clear both back and front buffers of tiled layer buffer. With those changes in place we can hook layer manager cache cleanup into gecko memory-pressure signal. The cleanup no longer causes failing asserts in the engine code and reduces memory usage on pages which can produce a lot of new layers during scrolling or panning.

### CODE REVIEW

**Comment by rainemak** [comment]
For bug 959089 there are at least two more commits. Not sure if they would make any diff:

"Bug 959089 - Separate GrallocBuffer allocations from Compositor thread(part1), r=vlad,gal" (in gecko github mirror SHA1 e3f80bb4ff87)
"Bug 959089 - Separate GrallocBuffer allocations from Compositor thread(part2). r=nical" (in gecko github mirror SHA1 01c16a7afc8a)

**Comment by tworaz** [comment]
Raine. I think you're referring to split patches that have landed on mozilla-inbound. On central only two patches have been merged. See this comment https://bugzilla.mozilla.org/show_bug.cgi?id=959089#c137

**Comment by rojkov** [comment]
LGTM

**Comment by rainemak** [comment]
LGTM! Works nicely with "low-memory" "memory-pressure".

**Comment by tworaz** [comment]
Note to myself, push this also to embedlite and embedlite_38 branches.

**Comment by rainemak** [comment]
MR https://git.merproject.org/mer-core/gecko-dev/merge_requests/4 obsoletes this one.

**Pull request closed without merging**
